### ISSUE TITLE
Update to newest cake version

### ISSUE THREAD

**Issue by Tynamix** [papauorg/Cake.Liquibase#1]
Hey,
could you please update your fabulous extension to the newest cake version? 

Thank you and viele grüße an den Bodensee aus Dresden ;),

Roman

**Comment by Lichtel** [comment]
That's a great idea! I'a big fan of this addin and would appreciate that, too!

Grüße auch aus Berlin 😄

Erik

**Comment by papauorg** [comment]
Thank you for your interest in the extension. :stuck_out_tongue_winking_eye: I just released a new version that supports Cake 0.26.1.
After indexing is complete you can find it on nuget.org (https://www.nuget.org/packages/Cake.Liquibase/0.1.6-preview).

Philipp
